### Partial update
PATCH http://localhost:8080/problems/2
Content-Type: application/json

{
    "difficulty": "MODERATE"
}

####
## Full update
PUT http://localhost:8080/problems/3
Content-Type: application/json

{
  "id": 3,
  "title": "Two Sum",
  "description": "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
  "difficulty": "EASY",

  "topics": [
    { "name": "Array" },
    { "name": "Hash Table" }
  ],

  "examples": [
    {
      "input": "nums = [2,7,11,15], target = 9",
      "output": "[0,1]",
      "explanation": "Because nums[0] + nums[1] == 9, we return [0,1]."
    },
    {
      "input": "nums = [3,2,4], target = 6",
      "output": "[1,2]",
      "explanation": "Because nums[1] + nums[2] == 6, we return [1,2]."
    }
  ],

  "problemConstraints": [
    { "text": "2 <= nums.length <= 10^4",
      "valueConstraint": true
    },
    { "text": "-10^9 <= nums[i] <= 10^9",
      "valueConstraint": true
    },
    { "text": "-10^9 <= target <= 10^9" ,
      "valueConstraint": true
    }
  ],
  "hints": [
    { "text": "A brute force solution is simple but inefficient." },
    { "text": "Try to use a hash map to achieve O(n) time complexity." }
  ],

  "testcases": [
    {
      "input": "2 7 11 15\n9",
      "expectedOutput": "0 1",
      "hidden": false
    },
    {
      "input": "3 2 4\n6",
      "expectedOutput": "1 2",
      "hidden": false
    },
    {
      "input": "3 3\n6",
      "expectedOutput": "0 1",
      "hidden": true
    }
  ]
}
